// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        DataPanel: typeof import("./src/components/ToolPanels/DataPanel/DataPanel.vue")["default"];
        Draggable: typeof import("./src/components/Draggable/Draggable.vue")["default"];
        Loading: typeof import("./src/components/Loading.vue")["default"];
        Sunbutton: typeof import("./src/components/Sunbutton/index.vue")["default"];
    }
}
